# Generated by Django 3.2.1 on 2021-07-22 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='categories_and_tag.categories', verbose_name='دسته بندی والد'),
        ),
    ]
