# Generated by Django 3.2.1 on 2021-07-22 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories_and_tag', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('detail', models.TextField(default='توضیحاتی وجود ندارد!', verbose_name='توضیحات')),
                ('city', models.IntegerField(choices=[(1, 'بوشهر'), (2, 'اصفهان'), (3, 'تهران')], verbose_name='شهر شما : ')),
                ('description', models.CharField(default='توضیحات', max_length=200)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('status', models.BooleanField(verbose_name='نمایش داده شود؟')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(to='categories_and_tag.Categories')),
                ('related_post', models.ManyToManyField(blank=True, to='post.Post')),
                ('tags', models.ManyToManyField(to='categories_and_tag.Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='متن نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification', models.BooleanField(default=False, verbose_name='نمایش داده شود ؟ ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='پست مورد نظر')),
            ],
        ),
    ]
