# Generated by Django 3.2.1 on 2021-07-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان نظر'),
        ),
    ]
