# Generated by Django 3.2.1 on 2021-07-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_tag', '0001_initial'),
        ('post', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='categories_and_tag.Categories'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='categories_and_tag.Tags'),
        ),
    ]
